feat(smtp) : Add smtp check capability
ycrumeyrolle/HealthCheck pull request #1
Opened 2017-02-20 09:21 UTC by sdib

2017-02-20 12:40 UTC, ycrumeyrolle requested changes

2017-02-20 12:40 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                            await writer.WriteLineAsync($"EHLO {settings.SmtpAddress}");
String allocation could be avoided. 
Maybe by doing once by the `SmtpWatchSettings`

2017-02-20 12:40 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                            if (smtpResponse.StartsWith("250"))
Use constant

2017-02-20 12:40 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                                context.Succeed(smtpResponse);
Be careful to avoid leak information. 
What are the possible SMTP responses ?

2017-02-20 12:40 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                                context.Fail(smtpResponse);
Same

2017-02-20 14:00 UTC, sdib commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                                context.Succeed(smtpResponse);
for the ehlo command, here are the responses : http://www.greenend.org.uk/rjk/tech/smtpreplies.html#EHLO

2017-02-20 14:09 UTC, sdib commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                                context.Fail(smtpResponse);
Do you think I should hide smtp server response ?
Information leak may be managed by protecting healthcheck endpoint ?

2017-02-20 21:28 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                    settings.UseSsl = false;
It would be better to throw a NotSupportedException.

2017-02-20 21:28 UTC, ycrumeyrolle commented on src/AspNetCore.HealthCheck.Smtp/SmtpWatcher.cs
> +                                context.Fail(smtpResponse);
We should avoid to expose informations like backend servers. 
But these messages are important for understanding the errors.
We may log errors #4.

2017-02-21 10:45 UTC, ycrumeyrolle approved these changes

2017-02-21 10:57 UTC, merged